import { motion } from "framer-motion";
import { ArrowUpRight, Coffee, Moon, Users } from "lucide-react";
import "./GavaPage.css";
const hero='https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=2000&q=88';
const room='https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=88';
const common='https://images.unsplash.com/photo-1522771739844-6a9f6e5f14af?auto=format&fit=crop&w=1600&q=88';
const cta='https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1800&q=88';
function GavaPage(){return <main className="gava-page"><section className="gava-hero"><img src={hero} alt="GAVA stay interior"/><div className="gava-shade"/><div className="gava-hero-inner"><span className="eyebrow">05 · GAVA STAY</span><h1>Stay a little<br/><em>longer.</em></h1><p>A relaxed stay above the café — made for curious travellers, slow mornings and conversations that run late.</p><a href="#stay" className="pill-light">Discover GAVA <ArrowUpRight size={16}/></a></div></section><section className="gava-intro" id="stay"><div className="page-container gava-intro-grid"><div><span className="eyebrow dark">MORE THAN A BED</span><h2>A place to sleep.<br/><em>A place to belong.</em></h2></div><p>GAVA is simple, social and comfortable. Come for a night, stay for a few days, and make the café downstairs part of your routine.</p></div></section><section className="gava-story"><div className="page-container gava-story-grid"><img src={room} alt="Comfortable GAVA room"/><div><span className="eyebrow dark">THE STAY</span><h2>Comfortable,<br/><em>not complicated.</em></h2><p>Clean rooms, thoughtful essentials and shared spaces designed to make meeting people feel natural.</p><div className="gava-perks"><div><Moon/><strong>Rest easy</strong><span>Simple, comfortable rooms.</span></div><div><Users/><strong>Meet people</strong><span>Shared spaces with a social feel.</span></div><div><Coffee/><strong>Café downstairs</strong><span>Good coffee, whenever you want it.</span></div></div></div></div></section><section className="gava-common"><div className="page-container"><img src={common} alt="Shared accommodation space"/><div className="gava-common-copy"><span className="eyebrow dark">COMMON GROUND</span><h2>The best stories<br/><em>start casually.</em></h2><p>Grab a coffee, meet another traveller, ask where they are headed. GAVA keeps the common spaces open to possibility.</p></div></div></section><section className="image-cta" style={{backgroundImage:`url(${cta})`}}><div className="image-cta-overlay"/><div className="image-cta-inner"><span className="eyebrow">READY TO STAY?</span><h2>Your room<br/><em>is waiting.</em></h2><a href="/book-table" className="pill-light">Ask about GAVA <ArrowUpRight size={16}/></a></div></section></main>}
export default GavaPage;
