import { motion } from "framer-motion";
import { ArrowUpRight, CalendarDays, Sparkles, Users } from "lucide-react";
import "./EventPage.css";
const hero='https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=2000&q=88';
const eventImg='https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=88';
const cta='https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1800&q=88';
const events=[['Private Dining','Intimate dinners, birthdays and celebrations shaped around your people.'],['Community Evenings','Small gatherings, conversations, workshops and nights with a little more character.'],['Brand & Corporate','A warm, relaxed setting for launches, team dinners and creative get-togethers.']];
function EventPage(){return <main className="events-page"><section className="events-hero"><img src={hero} alt="Warm dinner event"/><div className="events-shade"/><div className="events-hero-inner"><span className="eyebrow">04 · GATHER HERE</span><h1>Make it<br/><em>memorable.</em></h1><p>From intimate dinners to lively evenings, De Verde gives good gatherings a warm place to happen.</p><a href="#event-types" className="pill-light">Explore events <ArrowUpRight size={16}/></a></div></section><section className="events-intro"><div className="page-container"><span className="eyebrow dark">WHAT WE HOST</span><h2>Good spaces make<br/><em>good memories.</em></h2><p>We keep events personal, relaxed and beautifully considered — with food, drinks and hospitality taken care of.</p></div></section><section className="event-types" id="event-types"><div className="page-container event-layout"><img src={eventImg} alt="Guests gathering around a dining table"/><div className="event-cards">{events.map((e,i)=><motion.article key={e[0]} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><span>0{i+1}</span><div><h3>{e[0]}</h3><p>{e[1]}</p></div><ArrowUpRight size={18}/></motion.article>)}</div></div></section><section className="event-details"><div className="page-container event-details-grid"><div><span className="eyebrow dark">THE DETAILS</span><h2>Small touches.<br/><em>Big feeling.</em></h2></div><div className="detail-list"><div><CalendarDays/><strong>Flexible dates</strong><p>Tell us what you are planning and we will help shape the evening.</p></div><div><Users/><strong>Small to medium gatherings</strong><p>Perfect for dinners, celebrations, meetings and community nights.</p></div><div><Sparkles/><strong>Thoughtful hospitality</strong><p>Food, drinks and a warm room that lets people focus on being together.</p></div></div></div></section><section className="image-cta event-cta" style={{backgroundImage:`url(${cta})`}}><div className="image-cta-overlay"/><div className="image-cta-inner"><span className="eyebrow">PLANNING SOMETHING?</span><h2>Let's make<br/><em>it happen.</em></h2><a href="/contact" className="pill-light">Start a conversation <ArrowUpRight size={16}/></a></div></section></main>}
export default EventPage;
